drop table avaliacao_profissional if exists;
drop table centro_custo if exists;
drop table criterio_avaliacao if exists;
drop table empresa if exists;
drop table funcionario if exists;
drop table role if exists;
drop table user if exists;
drop table user_role if exists;
drop table valor_empresa if exists;

create table avaliacao_profissional (
   id bigint generated by default as identity,
    comentarios_bp varchar(600),
    comentarios_gerente varchar(600),
    comentarios_mentor varchar(600),
    data_aprovacao_gerente timestamp,
    data_avaliacao_bp timestamp,
    data_avaliacao_mentor timestamp,
    data_criacao timestamp not null,
    nota_final double not null,
    ressalvas_gerente varchar(600),
    status varchar(32) not null,
    bp_avaliador_id bigint,
    funcionario_id bigint not null,
    gerente_aprovador_id bigint,
    mentor_avaliador_id bigint,
    primary key (id)
);

create table centro_custo (
   id bigint generated by default as identity,
    endereco varchar(255) not null,
    nome varchar(255) not null,
    empresa_id bigint not null,
    gerente_id bigint,
    primary key (id)
);

create table criterio_avaliacao (
   id bigint generated by default as identity,
    nota_bp integer,
    nota_mentor integer,
    avaliacao_id bigint not null,
    valor_empresa_id bigint not null,
    primary key (id)
);

create table empresa (
   id bigint generated by default as identity,
    cnpj varchar(255) not null,
    nome_fantasia varchar(255) not null,
    razao_social varchar(255) not null,
    primary key (id)
);

create table funcionario (
   id bigint generated by default as identity,
    cargo varchar(32) not null,
    cpf varchar(255) not null,
    data_admissao timestamp not null,
    data_promocao timestamp,
    nivel integer not null,
    nome varchar(255) not null,
    centro_custo_id bigint not null,
    empresa_id bigint not null,
    mentor_id bigint,
    usuario_id bigint not null,
    primary key (id)
);

create table role (
   id bigint generated by default as identity,
    name varchar(60),
    primary key (id)
);

create table user (
   id bigint generated by default as identity,
    email varchar(50),
    name varchar(50),
    password varchar(100),
    username varchar(50),
    primary key (id)
);

create table user_role (
   user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id)
);

create table valor_empresa (
   id bigint generated by default as identity,
    descricao varchar(255) not null,
    peso double not null,
    empresa_id bigint not null,
    primary key (id)
);

alter table empresa add constraint UK_74xhe5obsc7li6x4q5wi75pd5 unique (cnpj);
alter table funcionario add constraint UK_rxosr8731eb3gbnlbt2mqfan8 unique (cpf);
alter table role add constraint UK_epk9im9l9q67xmwi4hbed25do unique (name);
alter table user add constraint UKsb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);

alter table avaliacao_profissional add constraint FK4j8h085t0dabfs7w3mai4d6g0 foreign key (bp_avaliador_id) references funcionario;
alter table avaliacao_profissional add constraint FKr0wd5c1sntgvk5vywt3tbj7 foreign key (funcionario_id) references funcionario;
alter table avaliacao_profissional add constraint FKlk49164gl3vi7jmwd9xhm7luk foreign key (gerente_aprovador_id) references funcionario;
alter table avaliacao_profissional add constraint FKq8osdwrmds6hoe0tiy0sjnyw2 foreign key (mentor_avaliador_id) references funcionario;
alter table centro_custo add constraint FKrhtqpv54ty5tp2i24vfqiydco foreign key (empresa_id) references empresa;
alter table centro_custo add constraint FK9jbmh42idj4l83pa6amtcm7f7 foreign key (gerente_id) references funcionario;
alter table criterio_avaliacao add constraint FKls9e956x3vmvx09kq8b360mj0 foreign key (avaliacao_id) references avaliacao_profissional;
alter table criterio_avaliacao add constraint FKoo5mvm177r7110ar4x6cdeorf foreign key (valor_empresa_id) references valor_empresa;
alter table funcionario add constraint FKk7ldyolsyvv0kd7lq0kp350vp foreign key (centro_custo_id) references centro_custo;
alter table funcionario add constraint FK4cm1kg523jlopyexjbmi6y54j foreign key (empresa_id) references empresa;
alter table funcionario add constraint FKmsvy8vg749s66jkbmd0if7du foreign key (mentor_id) references funcionario;
alter table funcionario add constraint FKc1bold2vfh9s5ey9a22bi9gq9 foreign key (usuario_id) references user;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user;
alter table valor_empresa add constraint FKnda5j5rtgsr1y3ylw5sy9ofbs foreign key (empresa_id) references empresa;
